src/entries/DrugChartModal/DrugChartModal.jsx
src/entries/DrugChartModal/DrugChartModal.spec.jsx
src/entries/DrugChartModal/DrugChartModalTestUtils.js

Jira link https://bahmni.atlassian.net/browse/BAH-3167

BAH-3167 | Fetch schedule time recommendation based on certain strategy

---

.github/scripts/transifex.sh
.github/workflows/build_publish.yml
.tx/config

Jira -> [BAH-3002](https://bahmni.atlassian.net/browse/BAH-3002)
In this PR, we have added a script that does the following :
1. Check if Transifex CLI is installed. If not installed, install the latest Transifex CLI.
2. Check if the transifex config file is present in the repo at root/.tx/config.
3. Push the translation source file to transifex by running tx push -s.
4. If a error message is thrown, capture the error.
Additionally, the .tx/config file has been migrated to latest Client definition.

BAH-3002 | Add. Script To Push Translations To Transifex

---

src/features/DisplayControls/NursingTasks/components/TaskTile.jsx
src/features/DisplayControls/NursingTasks/styles/TaskTile.scss
src/features/DisplayControls/NursingTasks/tests/NursingTasks.spec.jsx
src/features/DisplayControls/NursingTasks/tests/__snapshots__/NursingTasks.spec.jsx.snap
src/features/DisplayControls/NursingTasks/tests/__snapshots__/TaskTile.spec.jsx.snap

https://bahmni.atlassian.net/browse/BAH-3313

Sowmya | BAH-3313 | To add Nursing Tasks display control in new IPD dashboard

---

src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js
src/features/DrugChart/DrugChartWrapper/DrugChartWrapper.jsx
src/features/DrugChart/DrugChartWrapper/DrugChartWrapper.spec.jsx
src/features/DrugChart/DrugChartWrapper/DrugChartWrapperMockData.js

Asana - https://app.asana.com/0/1204322126657135/1205974389432443
As part of the above card, now each slot will have the order id against it, Instead of the Schedule having them. Due to this, the response from the API would be changed a bit and hence changing the data extraction logic

 A-1205974389432443 | Feedbacks on Medication Schedule

---

public/i18n/locale_en.json
src/components/DrugChartSlider/DrugChartSlider.jsx
src/components/DrugChartSlider/DrugChartSlider.scss
src/components/DrugChartSlider/DrugChartSlider.spec.jsx
src/components/DrugChartSlider/DrugChartSliderNotification.jsx
src/components/DrugChartSlider/DrugChartSliderNotification.scss
src/components/DrugChartSlider/__snapshots__/DrugChartSlider.spec.jsx.snap
src/entries/Dashboard/Dashboard.jsx
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasks.spec.jsx
src/features/DisplayControls/Treatments/components/Treatments.jsx
src/features/DisplayControls/Treatments/styles/Treatments.scss
src/features/DisplayControls/Treatments/tests/Treatments.spec.jsx
src/features/SideBarPanel/components/SideBarPanelClose.jsx

Asana 
- https://app.asana.com/0/1204322126657135/1205801410099371
- https://app.asana.com/0/1204322126657135/1204941331551263
This PR has changes to
- handle schedules in Drug Chart when patient gets admitted later in the day
- refreshing of nursing tasks display control on save of medication
- Cancel and Close pop up on any edits in the Drug Chart

[Sowmya | Arjun] | Drug Chart slider changes for patient getting admitted later in the day

---

public/i18n/locale_en.json
src/constants.js
src/entries/CareViewDashboard/CareViewDashboard.jsx
src/entries/CareViewDashboard/CareViewDashboard.scss
src/entries/CareViewDashboard/CareViewDashboard.spec.jsx
src/entries/CareViewDashboard/CareViewDashboardUtils.js
src/entries/CareViewDashboard/__snapshots__/CareViewDashboard.spec.jsx.snap
src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/CareViewPatients/styles/CareViewPatients.scss
src/features/CareViewSummary/components/CareViewSummary.jsx
src/features/CareViewSummary/styles/CareViewSummary.scss
src/index.js
webpack.config.js

Asana - https://app.asana.com/0/1204322126657135/1205974326537693
This PR has changes to build the new Care View Dashboard. The changes creates a basic skeleton of the page with dummy fields.

Arjun | A-1205974326537693 | To build a page in React for new Ward-level patients dashboard

---

src/features/DrugChartSlider/utils/DrugChartSliderUtils.js

Asana: https://app.asana.com/0/1204322126657135/1205821184257091/f

update. to show start time for stat medication

---

src/components/ExpandableDataTable/ExpandableDataTable.jsx
src/components/ExpandableDataTable/ExpandableDataTable.scss
src/components/ExpandableDataTable/ExpandableDataTable.spec.jsx
src/components/VerticalTabs/VerticalTabs.jsx
src/components/VerticalTabs/VerticalTabs.scss
src/components/VerticalTabs/VerticalTabs.spec.jsx
src/features/DisplayControls/Diagnosis/components/Diagnosis.jsx
src/features/DisplayControls/Diagnosis/components/DiagnosisExpandableRow.jsx
src/features/DisplayControls/Diagnosis/styles/Diagnosis.scss
src/features/DisplayControls/Diagnosis/styles/DiagnosisExpandableRow.scss
src/features/DisplayControls/Diagnosis/tests/Diagnosis.spec.jsx
src/features/DisplayControls/Diagnosis/tests/DiagnosisExpandableRow.spec.jsx
src/features/DisplayControls/Treatments/components/ExpandableRowData.jsx
src/features/DisplayControls/Treatments/components/TreatmentExpandableRow.jsx
src/features/DisplayControls/Treatments/components/Treatments.jsx
src/features/DisplayControls/Treatments/styles/Treatments.scss
src/features/DisplayControls/Treatments/tests/ExpandableRowData.spec.jsx
src/features/DisplayControls/Treatments/tests/Treatments.spec.jsx
src/icons/notes.svg

Tanya| Ability to display Notes in Diagnosis section and Instructions and Additional Instructions in Treatments section in the new IPD dashboard |https://app.asana.com/0/1204322126657135/1205947474146055

Display Notes/Instructions

---

public/i18n/locale_en.json
src/entries/Dashboard/Dashboard.jsx
src/features/DisplayControls/PatientHeader/components/PatientHeader.jsx
src/features/DisplayControls/PatientHeader/styles/PatientHeader.scss
src/features/DisplayControls/PatientHeader/tests/__snapshots__/PatientHeader.spec.jsx.snap

https://app.asana.com/0/1204322126657135/1206201729443040
This PR has changes to add navigation links to Discharge Summary and Patient Dashboard.

A-1206201729443040 | Navigation to clinical dashboard and discharge summary tab from IPD dashboard

---

src/features/DisplayControls/DrugChart/components/DrugListCell.jsx
src/features/DisplayControls/DrugChart/styles/DrugListCell.scss
src/features/DisplayControls/DrugChart/tests/__snapshots__/DrugChart.spec.jsx.snap
src/features/DisplayControls/DrugChart/tests/__snapshots__/DrugListCell.spec.js.snap
src/features/DisplayControls/NursingTasks/components/TaskTile.jsx
src/features/DisplayControls/NursingTasks/styles/TaskTile.scss

Abi| fix. styling issue for stopped meication and in nursing tasks modal

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/styles/TaskTile.scss

1. Fixed padding issue for clock and timestamp when drug name is long
2. Fixed padding issue for Loading text in Nursing Tasks display control

Abi | fix. padding issues in nursing task

---

src/components/VerticalTabs/VerticalTabs.scss

Arjun | Fix css issues bleeding into medication tab

---

src/constants.js
src/features/DisplayControls/Allergies/components/Allergies.jsx
src/features/DisplayControls/Allergies/components/Allergies.spec.jsx
src/features/DisplayControls/NursingTasks/components/AdministeredMedicationList.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/__snapshots__/AdministeredMedicationList.spec.jsx.snap
src/features/DisplayControls/NursingTasks/utils/TaskTileUtils.js
src/features/DisplayControls/Vitals/tests/__snapshots__/Vitals.spec.jsx.snap
src/features/DisplayControls/Vitals/utils/VitalsUtils.js
src/utils/DateTimeUtils.js

1206295776077332
1206293736141196
1206293736141174
1206293736141135
1206293736141126

Ayush | 1206295776077332 | fixed multiple bugs on IPD Dashboard

---

src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

- fix disable save for empty doseunits and route (https://app.asana.com/0/1204322126657135/1206372342900595/f)
- fix sorting for administered tasks (https://app.asana.com/0/1204322126657135/1206379778527480/f)

[Bug] Kavitha | Emergency task bugs

---

src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

Bug card : https://app.asana.com/0/1204322126657135/1206403830594863/f

Kavitha | fix sorting order in nursing task tiles

---

src/features/DrugChartSlider/components/DrugChartSlider.jsx
src/features/DrugChartSlider/components/ScheduleSection.jsx
src/features/DrugChartSlider/utils/DrugChartSliderUtils.js

- fix reminder slot mismatch in edit drug chart flow
- remove subsequent slots row from add and edit if the schedule is for 1 day
- fix ascending order UI error in reminder slots row
Bug cards:
1. https://app.asana.com/0/1204322126657135/1206334458964232/f
2. https://app.asana.com/0/1204322126657135/1206334458964230/f
3. https://app.asana.com/0/1204322126657135/1206100980858094/f

Kavitha | fix schedule timings bugs in add and edit drug chart flow

---

src/features/DisplayControls/Treatments/utils/TreatmentsUtils.js

fix blank screen issue on add nursing task

[Sri/Kalai] - fix blank screen issue on add nursing task

---

src/features/DisplayControls/Treatments/tests/TreatmentsUtils.spec.jsx
src/features/DisplayControls/Treatments/utils/TreatmentsUtils.js

1. Fix color in status : "Not acknowledge" to red
2. Fix drug name stricked out when there is no instructions

[Sri] - Fix styling in stop drug flow

---

src/features/DisplayControls/DrugChart/components/DrugListCell.jsx
src/features/DisplayControls/DrugChart/components/SVGIcon.jsx
src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js

Asna: https://app.asana.com/0/1204322126657135/1206389781267740/f

Abi | add. stopped flow in drug chart

---

src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/tests/__snapshots__/AddEmergencyTasks.spec.jsx.snap
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js
src/features/DrugChartSlider/components/DrugChartSlider.jsx

Bug fixes:
1206503240343316
1206503240343309

fix: stop status in nursing task and disable save button during API call

---

src/features/DisplayControls/DrugChart/components/DrugListCell.jsx
src/features/DisplayControls/DrugChart/styles/DrugListCell.scss

Bug card: https://app.asana.com/0/1204322126657135/1206167529045924/f

Kavitha | add administered times tooltip in drug chart

---

src/features/DisplayControls/DrugChart/components/DrugListCell.jsx
src/features/DisplayControls/DrugChart/styles/DrugListCell.scss
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/Treatments/styles/Treatments.scss
src/features/DisplayControls/Treatments/utils/TreatmentsUtils.js

This fixes:
1. Fix the tags in Treatments display control
2. Fix drugName not wrapping in some scenarios.
3. Skipped drug payload to accept administeredTime as Schedule Time

Phani | Fix misc. issues

---

src/features/DisplayControls/Treatments/components/Treatments.jsx

fix stop drug for previous date

[Sri/Kalai] - fix stop drug for previous date

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

Missed to handle for pending and for PRN nursing tasks

Fix the pending nursing task read mode functionality

---

src/features/DisplayControls/DrugChart/tests/DrugChartView.spec.jsx
src/features/DisplayControls/DrugChart/tests/DrugChartViewMockData.js
src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/components/TaskTile.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/tests/TaskTile.spec.jsx
src/features/DisplayControls/NursingTasks/tests/UpdateNursingTasks.spec.jsx

Asana Link: https://app.asana.com/0/1204322126657135/1206260271506844/f

Prn task save

---

package.json
src/constants.js
src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx
src/features/DisplayControls/NursingTasks/components/AdministeredMedicationList.jsx
src/features/DisplayControls/NursingTasks/styles/EmergencyTasks.scss
src/features/DisplayControls/NursingTasks/tests/AddEmergencyTasks.spec.jsx
src/features/DisplayControls/NursingTasks/tests/__snapshots__/AddEmergencyTasks.spec.jsx.snap
src/features/DisplayControls/NursingTasks/tests/__snapshots__/AdministeredMedicationList.spec.jsx.snap
src/features/DrugChartSlider/components/DrugChartSlider.jsx
src/features/DrugChartSlider/utils/DrugChartSliderUtils.js
src/utils/DateTimeUtils.js
yarn.lock

Asana: https://app.asana.com/0/1204322126657135/1206590423877638/f

Abi | fix. include 12hr time format in add emergency tasks

---

src/entries/Dashboard/Dashboard.jsx
src/features/DisplayControls/PatientHeader/components/PatientHeader.jsx
src/features/DisplayControls/PatientHeader/tests/PatientHeader.spec.jsx

Display control selected is getting overlapped by patient details | A-https://app.asana.com/0/1204322126657135/1206522048129372|

Tanya| fix. sections getting overlapped by patient details

---

src/features/DisplayControls/Treatments/components/Treatments.jsx

Tanya | Cherry Pick PR 130 

---

public/i18n/locale_en.json
src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtils.spec.js
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js
src/features/DisplayControls/NursingTasks/utils/TaskTileUtils.js
src/features/DisplayControls/NursingTasks/utils/constants.js

A-https://app.asana.com/0/1204322126657135/1206251977416816/ | Ability to indicate Missed medication dose by system and displaying the same in the Nursing Tasks and Drug Chart display controls

Ability to indicate Missed medication dose by system and displaying the same in the Nursing Tasks and Drug Chart display controls

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DrugChartSlider/components/DrugChartSlider.jsx

PR has changes to fix
- PRN placeholder not shwoing up in pending section on the first load
- Drug chart Slider Edit cycle failing in 12 hour clocks

IPD Pre release fixes

---

src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js
src/features/DisplayControls/Treatments/utils/TreatmentsUtils.js
src/features/DrugChart/DrugChartWrapper/DrugChartWrapper.jsx
src/features/DrugChartSlider/components/DrugChartSlider.jsx
src/features/DrugChartSlider/tests/DrugChartSlider.spec.jsx
src/features/DrugChartSlider/tests/__snapshots__/DrugChartSlider.spec.jsx.snap
src/features/DrugChartSlider/utils/DrugChartSliderTestUtils.js

JIRA ref: [BAH-3651](https://bahmni.atlassian.net/browse/BAH-3651)

BAH-3651 | Kavitha | add scheduling continuous medications

---

.github/scripts/transifex.sh
.github/workflows/build_publish.yml
.github/workflows/pull_translations.yml

This workflow is designed to retrieve translations from Transifex once every month in case resources are updated.

[Rahu] | BAH-3644 | Add. Workflow To Pull Translations

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtils.spec.js
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtilsMockData.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

Tanya | A-1206687182697884 | https://app.asana.com/0/1204322126657135/1206687182697884

When a scheduled medication task is not updated and the next dose is due, then system should make the corresponding task tile as non-clickable

---

src/features/DisplayControls/Allergies/components/Allergies.jsx
src/features/DisplayControls/Allergies/components/Allergies.spec.jsx
src/features/DisplayControls/Allergies/components/AllergiesTestUtils.js
src/features/DisplayControls/Diagnosis/components/Diagnosis.jsx
src/features/DisplayControls/Diagnosis/tests/Diagnosis.spec.jsx
src/features/DisplayControls/Diagnosis/tests/DiagnosisMockData.js
src/utils/DateTimeUtils.js

A - 1206687182697896
Newly captured allergy / diagnosis info post a concluded IPD visit should not be reflected in the inactive IPD Dashboard

Show allergy and diagnosis based on ipd visit

---

src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/CareViewPatients/components/CareViewPatientsHeader.jsx
src/features/CareViewPatients/styles/CareViewPatients.scss
src/features/CareViewPatients/styles/CareViewPatientsHeader.scss
src/features/CareViewPatients/test/CareViewPatients.spec.jsx
src/features/CareViewPatients/test/CareViewPatientsHeader.spec.jsx
src/features/CareViewPatientsSummary/components/CareViewPatientsSummary.jsx
src/features/CareViewPatientsSummary/styles/CareViewPatientsSummary.scss
src/features/CareViewPatientsSummary/tests/CareViewPatientsSummary.spec.jsx
src/features/CareViewPatientsSummary/tests/CareViewPatientsSummaryMock.js
src/features/CareViewPatientsSummary/tests/__snapshots__/CareViewPatientsSummary.spec.jsx.snap
src/utils/CommonUtils.jsx
src/utils/DateTimeUtils.js

Asana Link: https://app.asana.com/0/1204322126657135/1206514083860597/f

Add ward navigation feature with timeframe compatible

---

src/features/DrugChartSlider/components/DrugChartSlider.jsx
src/features/DrugChartSlider/tests/DrugChartSlider.spec.jsx

A-https://app.asana.com/0/1204322126657135/1206687182697892/f | Modification to the previous requirements

Update the scheduled time for enabled slots with current time in Add to Drug Chart Slider

---

src/utils/DateTimeUtils.js

Adding hot-fix to handle navigation in care view dashboard which became flaky after making changes in IPD Dashboard.

Fix Navigation in Care View Dashboard

---

src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/DisplayControls/DrugChart/components/DrugChartView.jsx
src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx

This is to fix the navigation in care view dashboard when the shift timings have half-hours eg: 08:30 - 16:00

Fix Care view dashboard for half hour shift timings

---

src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/CareViewPatientsSummary/components/CareViewPatientsSummary.jsx

https://app.asana.com/0/1204322126657135/1207062100381645/f
https://app.asana.com/0/1204322126657135/1207062100381631/f

Bug fix | Care View Dashboard changes for handling patient summary in two dates

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

-feedbacks for JIRA [BAH-3753](https://bahmni.atlassian.net/browse/BAH-3753)

Kavitha|removed notes for done task and time for skip task

---

src/features/DisplayControls/DrugChart/styles/DrugListCell.scss
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx

Asana - https://app.asana.com/0/search/1207109980834024/1206522048129359

Arjun | Notes are getting hidden under Rx stat tag [ Tablet view ]

---

src/features/CareViewSummary/components/CareViewSummary.jsx
src/features/DisplayControls/Treatments/components/Treatments.jsx

A-1207130871600195 | Feedback work - addressing Rx Future Start Date in PRN and non-PRN Workflows & retaining ward context of Nurse | https://app.asana.com/0/1204322126657135/1207130871600195/

Feedback Work

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx

https://app.asana.com/0/1204322126657135/1207238176349499/f

A-1207238176349499 | Stopped nursing tasks not showing up in the current shift

---

public/i18n/locale_en.json
src/constants.js
src/entries/Dashboard/componentMapping.js
src/features/DisplayControls/IntakeOutput/utils/IntakeOutputUtils.js
src/features/DisplayControls/PatientFeedingRecord/components/PatientFeedingRecord.jsx
src/features/DisplayControls/PatientFeedingRecord/components/PatientFeedingRecordTable.jsx
src/features/DisplayControls/PatientFeedingRecord/styles/PatientFeedingRecord.scss
src/features/DisplayControls/PatientFeedingRecord/tests/__snapshots__/patientFeedingRecord.spec.jsx.snap
src/features/DisplayControls/PatientFeedingRecord/tests/patientFeedingRecord.spec.jsx
src/features/DisplayControls/PatientFeedingRecord/utils/PatientFeedingRecordUtils.js
src/utils/CommonUtils.jsx

Patient feeding record chart | https://app.asana.com/0/1204322126657135/1207131329940344

Patient Feeding Record Chart

---

src/constants.js
src/context/AllMedications.jsx
src/features/DisplayControls/DrugChart/components/DrugChartView.jsx
src/features/DisplayControls/DrugChart/utils/DrugChartUtils.js
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js
src/features/DisplayControls/Treatments/components/Treatments.jsx

Asana: https://app.asana.com/0/1204322126657135/1207086955567548/f

Abi | add. error message when api fails

---

src/features/DisplayControls/IntakeOutput/components/IntakeOutput.jsx
src/features/DisplayControls/IntakeOutput/styles/IntakeOutputTable.scss
src/features/DisplayControls/PatientFeedingRecord/components/PatientFeedingRecord.jsx
src/features/DisplayControls/PatientFeedingRecord/tests/__snapshots__/patientFeedingRecord.spec.jsx.snap

JIRA - https://bahmni.atlassian.net/browse/BAH-3946?atlOrigin=eyJpIjoiOTIyMWIxNmYxZTZjNDM2Mzg5OTE5YjBmYTFjYzY5ZWEiLCJwIjoiaiJ9
This PR fixes the css issue show in the above card for Intake Output and Patient Feeding Display controls

BAH-3946 | Bahmniapps CSS bleeding into Intake Output display control

---

src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/CareViewPatients/utils/CareViewPatientsUtils.js

Asana - https://app.asana.com/0/1204322126657135/1207053820490648
This PR adds bed number sorting logic to existing patient fetch endpoint in different wards in the Ward-level patient dashboard. 
Along with the existing logic to sort in the SQL query, a utility function had to be written to sort pure integer bed numbers

A-1207053820490648 | [CURE IPD Bug] - Patients are not arranged in ascending order of bed number

---

README.md
src/entries/CareViewDashboard/CareViewDashboard.spec.jsx
src/entries/CareViewDashboard/__snapshots__/CareViewDashboard.spec.jsx.snap
src/features/CareViewPatients/components/CareViewPatients.jsx
src/features/CareViewPatients/test/CareViewPatients.spec.jsx
src/features/CareViewPatients/utils/CareViewPatientsUtils.js
src/features/CareViewSummary/components/CareViewSummary.jsx
src/features/CareViewSummary/tests/CareViewSummary.spec.jsx
src/features/CareViewSummary/utils/CareViewSummary.js

JIRA -> [BAH-3981](https://bahmni.atlassian.net/browse/BAH-3981)
In this PR, a check has been introduced to block any unnecessary calls being made to `openmrs/ws/rest/v1/ipd/wards/undefined/patients?offset=0&limit=10`. This would help resolve the mismatch in Patient List In Care View Dashboard.

BAH-3981 | Fix. Mismatch in Patient List In Care View Dashboard

---

src/components/ExpandableDataTable/ExpandableDataTable.jsx

JIRA -> [BAH-3947](https://bahmni.atlassian.net/browse/BAH-3947)

BAH-3947 | Fix. Treatments Duplication In IPD Dashboard

---

src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtils.spec.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

…ckable when there are more than one.

BAH-4019 | Remove the logic that makes non medication task as non clickable when there are more than one

---

src/constants.js
src/features/DisplayControls/PatientHeader/utils/PatientHeaderUtils.js
src/features/DisplayControls/Treatments/utils/TreatmentsUtils.js

JIRA -> [BAH-4059](https://bahmni.atlassian.net/browse/BAH-4059)
This PR aims to refactor the IPD Dashboard to remove its dependency on the `openmrs/app/clinical/app.json` file by sourcing all required configurations from the `openmrs/app/ipdDashboard/app.json` file. This change will help avoid unnecessary ambiguity by ensuring that all IPD-specific configurations are maintained within the IPD module.

BAH-4059 | Refactor. Get IPD Dashboard Config from ipdDashboard

---

src/features/DisplayControls/NursingTasks/components/TaskTile.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/styles/TaskTile.scss
src/features/DisplayControls/NursingTasks/styles/UpdateNursingTasks.scss
src/features/DisplayControls/NursingTasks/tests/__snapshots__/TaskTile.spec.jsx.snap
src/features/DisplayControls/NursingTasks/tests/__snapshots__/UpdateNursingTasks.spec.jsx.snap

JIRA -> [BAH-4046](https://bahmni.atlassian.net/browse/BAH-4046)
This PR, aims to enhance the Task Slider to display the provider name on the task tile for non-medication tasks. This feature will improve transparency and accountability by clearly indicating which provider is responsible for each non-medication task.
| Updated Task Tile | Provider Name in Task Slider |
|-|-|
| ![Screenshot 2024-08-02 at 9 37 04 AM](https://github.com/user-attachments/assets/4c96a795-e633-4a87-b197-178417b6559d) | ![Screenshot 2024-08-02 at 9 37 11 AM](https://github.com/user-attachments/assets/117270f9-832b-4af4-a5d6-7e1ccc292dd2) |

BAH-4046 | Add. Provider Information on the Non-Medication Tasks Slider

---

src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/UpdateNursingTasks.spec.jsx

JIRA -> [BAH-4051](https://bahmni.atlassian.net/browse/BAH-4051)
This PR aims to integrate audit logging for non-medication tasks within the IPD Dashboard to ensure that every successfully added non-medication task is appropriately logged.

BAH-4051 | Add. Audit Log Support For Non Medication Tasks

---

src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx

- fix null check issue for dosage form while adding emergency medication

Kavitha | Dosage form null check for emergency medication

---

src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasksUtils.spec.js
src/features/DisplayControls/NursingTasks/utils/EmergencyTasksUtils.js
src/features/DisplayControls/NursingTasks/utils/NursingTasksUtils.js

JIRA -> [BAH-4050](https://bahmni.atlassian.net/browse/BAH-4050)
This PR aims to enhance the IPD Dashboard to handle network call failures for nursing tasks activities by displaying an error notification with a custom message when a network call fails.

BAH-4050 | Fix. Exception Handling for Nursing Tasks

---

src/constants.js
src/entries/Dashboard/Dashboard.jsx
src/features/DisplayControls/NursingTasks/components/AddEmergencyTasks.jsx
src/features/DisplayControls/NursingTasks/components/NursingTasks.jsx
src/features/DisplayControls/NursingTasks/components/UpdateNursingTasks.jsx
src/features/DisplayControls/NursingTasks/tests/AddEmergencyTasks.spec.jsx
src/features/DisplayControls/NursingTasks/tests/NursingTasks.spec.jsx
src/features/DisplayControls/NursingTasks/tests/UpdateNursingTasks.spec.jsx
src/features/DisplayControls/PatientHeader/components/PatientHeader.jsx
src/features/DisplayControls/PatientHeader/tests/PatientHeader.spec.jsx
src/features/DisplayControls/Treatments/components/Treatments.jsx
src/features/DisplayControls/Treatments/tests/Treatments.spec.jsx
src/utils/CommonUtils.jsx
src/utils/mockUserData.js

This PR adds privilege checks for user actions on the IPD Dashboard.
JIRA: https://bahmni.atlassian.net/browse/BAH-4062

BAH-4062 | Add Privilege checks for action buttons in Patient Dashboard

---

LICENSE
package.json

This PR updates the LICENSE of the repository from AGPL to MPLv2 with Healthcare Disclaimer

BAH-4077 | Refactor. Change LICENSE to MPLv2

---

.trivyignore
package.json
yarn.lock

JIRA -> [BAH-3717](https://bahmni.atlassian.net/browse/BAH-3717)

BAH-3717 | Update Packages To Fix Security Vulnerabilities

---

.github/workflows/build_publish.yml
package.json

JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.

BAH-4097 | Add. Bump Version 0.8 -> 1.0

---

src/constants.js
src/features/i18n/utils.js

https://app.asana.com/0/1204322126657135/1208586834272224

A-1208586834272224 | Intl support for micro-frontends

---

src/features/DisplayControls/Vitals/components/Vitals.jsx
src/features/DisplayControls/Vitals/utils/VitalsUtils.js

- Adds support that it'll intake either a single concept which is the default in the config or an array of configurable concepts (implementation specific) and show whatever value available for the patient under nutritional values.

Kavitha|adds array support for nutritional value concepts

---

.trivyignore
public/i18n/locale_en.json
public/i18n/locale_fr.json
src/features/CareViewPatientsSummary/components/PatientDetailsCell.jsx
src/features/CareViewPatientsSummary/tests/CareViewPatientsSummary.spec.jsx
src/features/CareViewPatientsSummary/tests/PatientDetailsCell.spec.jsx
src/features/CareViewPatientsSummary/tests/__snapshots__/CareViewPatientsSummary.spec.jsx.snap
src/features/CareViewPatientsSummary/tests/__snapshots__/PatientDetailsCell.spec.jsx.snap
src/features/DisplayControls/PatientHeader/components/PatientHeader.jsx
src/features/DisplayControls/PatientHeader/tests/PatientHeader.spec.jsx
src/features/DisplayControls/PatientHeader/tests/__snapshots__/PatientHeader.spec.jsx.snap
src/utils/DateTimeUtils.js

Added Age change in IPD Dashboard and Care view to show the Patient Age in Days, Months, Years instead of just Years.
Also added the test Suites to check the new Age logic in CareViewPatientsSummary, PatientHeader.jsx and PatientDetailsCell.jsx

Age in days months

---

src/utils/DateTimeUtils.js

In this I have updated the calculation of Age in days, Months and Years instead of just Age. I have also updated the from which day the DOB should be calculate.

Added updated Age calculation for IPD CareView
